# Displays available recipes by running `just -l`.
setup:
  #!/usr/bin/env bash
  just -l

# Locally install the "ud" script
i: 
  #!/usr/bin/env bash
  source ud.sh
  ud --help

# Run tests for "ud" script
test:
  #!/usr/bin/env bash
  go test ./...

