--- Track and restore the Mason packages used by this Neovim configuration.
---
--- The lock file is intentionally a plain, reviewable list of package@version
--- entries. :MasonLock refreshes it from the packages installed on this
--- machine. :MasonRestore installs missing entries without removing extras.

local M = {}

local lock_header =
  '# Generated by :MasonLock. Refresh this file after changing Mason packages.'

local function is_headless()
  return #vim.api.nvim_list_uis() == 0
end

local function notify(message, level)
  if is_headless() then
    if level >= vim.log.levels.ERROR then
      vim.api.nvim_err_writeln(message)
    else
      print(message)
    end
    return
  end

  vim.notify(message, level, { title = 'Mason lock' })
end

local function lock_path(path)
  return path or (vim.fn.stdpath('config') .. '/mason.lock')
end

local function read_lines(path)
  if vim.fn.filereadable(path) ~= 1 then
    return nil, ('lock file is not readable: %s'):format(path)
  end

  return vim.fn.readfile(path)
end

local function parse_entry(line, line_number)
  local name, version = line:match('^([^@%s]+)@([^%s]+)$')
  if not name or not name:match('^[%w][%w._-]*$') then
    return nil, ('invalid Mason lock entry on line %d: %s')
      :format(line_number, line)
  end

  return { name = name, version = version }
end

function M.read_lock(path)
  path = lock_path(path)
  local lines, read_error = read_lines(path)
  if not lines then
    return nil, { read_error }
  end

  local entries = {}
  local seen = {}
  local errors = {}

  for line_number, raw_line in ipairs(lines) do
    local line = vim.trim(raw_line)
    if line ~= '' and not line:match('^#') then
      local entry, parse_error = parse_entry(line, line_number)
      if not entry then
        errors[#errors + 1] = parse_error
      elseif seen[entry.name] then
        errors[#errors + 1] = ('duplicate Mason lock entry on line %d: %s')
          :format(line_number, entry.name)
      else
        seen[entry.name] = true
        entries[#entries + 1] = entry
      end
    end
  end

  table.sort(entries, function(left, right)
    return left.name < right.name
  end)

  if #errors > 0 then
    return nil, errors
  end

  return entries
end

local function write_lock(entries, path)
  local lines = { lock_header }
  for _, entry in ipairs(entries) do
    lines[#lines + 1] = ('%s@%s'):format(entry.name, entry.version)
  end

  local temporary_path = path .. '.tmp.' .. tostring(vim.fn.getpid())
  pcall(vim.fn.delete, temporary_path)
  local ok, write_result = pcall(vim.fn.writefile, lines, temporary_path)
  if not ok or write_result ~= 0 then
    return false, ('could not write temporary Mason lock: %s')
      :format(ok and tostring(write_result) or write_result)
  end

  local renamed = vim.fn.rename(temporary_path, path)
  if renamed ~= 0 then
    pcall(vim.fn.delete, temporary_path)
    return false, ('could not replace Mason lock: %s'):format(path)
  end

  return true
end

local function report_errors(errors)
  for _, message in ipairs(errors) do
    notify(message, vim.log.levels.ERROR)
  end
end

local function installed_package_entries(registry)
  local entries = {}
  local warnings = {}
  local package_names = registry.get_installed_package_names()
  table.sort(package_names)

  for _, name in ipairs(package_names) do
    if not registry.has_package(name) then
      warnings[#warnings + 1] =
        ('skipping installed Mason package not found in the registry: %s')
        :format(name)
    else
      local package = registry.get_package(name)
      local ok, version = pcall(package.get_installed_version, package)
      if not ok or not version then
        warnings[#warnings + 1] =
          ('skipping Mason package without an installed version: %s')
          :format(name)
      else
        entries[#entries + 1] = { name = name, version = version }
      end
    end
  end

  return entries, warnings
end

function M.refresh_lock(path)
  path = lock_path(path)
  local registry = require('mason-registry')
  local entries, warnings = installed_package_entries(registry)

  for _, warning in ipairs(warnings) do
    notify(warning, vim.log.levels.WARN)
  end

  local ok, write_error = write_lock(entries, path)
  if not ok then
    notify(write_error, vim.log.levels.ERROR)
    return false
  end

  notify(('wrote %d Mason packages to %s'):format(#entries, path),
    vim.log.levels.INFO)
  return true
end

local function package_root(path)
  return path or vim.env.MASON or (vim.fn.stdpath('data') .. '/mason')
end

local function is_directory(path)
  local stat = vim.uv.fs_stat(path)
  return stat ~= nil and stat.type == 'directory'
end

local function installed_package_names(root)
  local package_directory = root .. '/packages'
  local names = {}
  local scanner = vim.uv.fs_scandir(package_directory)
  if not scanner then
    return names
  end

  while true do
    local name, entry_type = vim.uv.fs_scandir_next(scanner)
    if not name then
      break
    end
    if entry_type == 'directory' then
      names[#names + 1] = name
    end
  end

  table.sort(names)
  return names
end

local function receipt_version(receipt_path)
  if vim.fn.filereadable(receipt_path) ~= 1 then
    return nil, 'receipt is missing'
  end

  local content = table.concat(vim.fn.readfile(receipt_path), '\n')
  local ok, receipt = pcall(vim.json.decode, content)
  if not ok or type(receipt) ~= 'table' then
    return nil, 'receipt is not valid JSON'
  end

  local source = receipt.source or receipt.primary_source
  local source_id = source and source.id
  if type(source_id) ~= 'string' then
    return nil, 'receipt has no package source ID'
  end

  local source_without_fragment = source_id:match('^[^#]+') or source_id
  local version = source_without_fragment:match('.*@([^@]+)$')
  if not version or version == '' then
    return nil, 'receipt source has no package version'
  end

  return version:gsub('%?.*$', '')
end

local function print_status(kind, message)
  local level = kind == 'error' and vim.log.levels.ERROR
    or kind == 'warning' and vim.log.levels.WARN
    or vim.log.levels.INFO
  notify(message, level)
end

function M.check(opts)
  opts = opts or {}
  local path = lock_path(opts.lock_path)
  local root = package_root(opts.mason_root)
  local entries, errors = M.read_lock(path)
  if not entries then
    report_errors(errors)
    return false
  end

  local locked_names = {}
  local failures = 0
  for _, entry in ipairs(entries) do
    locked_names[entry.name] = true
    local install_path = root .. '/packages/' .. entry.name
    local receipt_path = install_path .. '/mason-receipt.json'
    if not is_directory(install_path) then
      print_status('error', ('missing Mason package: %s'):format(entry.name))
      failures = failures + 1
    else
      local version, receipt_error = receipt_version(receipt_path)
      if not version then
        print_status('error', ('%s: %s'):format(entry.name, receipt_error))
        failures = failures + 1
      elseif version ~= entry.version then
        print_status('error', ('Mason version mismatch for %s: locked %s, installed %s')
          :format(entry.name, entry.version, version))
        failures = failures + 1
      end
    end
  end

  for _, name in ipairs(installed_package_names(root)) do
    if not locked_names[name] then
      print_status('warning', ('installed Mason package is not in mason.lock: %s')
        :format(name))
    end
  end

  if failures > 0 then
    print_status('error', ('Mason lock check failed with %d error(s)'):format(failures))
    return false
  end

  print_status('info', ('Mason lock check passed for %d package(s)'):format(#entries))
  return true
end

local function restore_entry(entry, registry)
  if not registry.has_package(entry.name) then
    return nil, ('Mason package is not available in the registry: %s')
      :format(entry.name)
  end

  local package = registry.get_package(entry.name)
  if package:is_installed() then
    local installed_version = package:get_installed_version()
    if installed_version ~= entry.version then
      return false, ('Mason version mismatch for %s: locked %s, installed %s')
        :format(entry.name, entry.version, installed_version)
    end
    return true
  end

  return { name = entry.name, version = entry.version, package = package }
end

local function install_missing_blocking(entries)
  local async = require('mason-core.async')
  return async.run_blocking(function()
    return async.wait_all(vim.tbl_map(function(entry)
      return function()
        return async.wait(function(resolve, reject)
          local ok, call_error = pcall(function()
            entry.package:install({ version = entry.version }, function(success, result)
              if success then
                resolve(result)
              else
                reject(result)
              end
            end)
          end)
          if not ok then
            reject(call_error)
          end
        end)
      end
    end, entries))
  end)
end

local function install_missing_interactive(entries, on_complete)
  local remaining = #entries
  local failures = {}
  local completed = false

  local function finish_if_done()
    if remaining == 0 and not completed then
      completed = true
      on_complete(failures)
    end
  end

  for _, entry in ipairs(entries) do
    local ok, call_error = pcall(function()
      entry.package:install({ version = entry.version }, function(success, result)
        if not success then
          failures[#failures + 1] = ('%s: %s'):format(entry.name, result)
        end
        remaining = remaining - 1
        finish_if_done()
      end)
    end)
    if not ok then
      failures[#failures + 1] = ('%s: %s'):format(entry.name, call_error)
      remaining = remaining - 1
      finish_if_done()
    end
  end

  finish_if_done()
end

function M.restore(path)
  path = lock_path(path)
  local entries, errors = M.read_lock(path)
  if not entries then
    report_errors(errors)
    return false
  end

  local registry = require('mason-registry')
  local refreshed, refresh_error = registry.refresh()
  if not refreshed then
    notify(('could not refresh the Mason registry: %s'):format(refresh_error),
      vim.log.levels.ERROR)
    return false
  end

  local missing = {}
  local failures = {}
  for _, entry in ipairs(entries) do
    local result, message = restore_entry(entry, registry)
    if result == nil or result == false then
      failures[#failures + 1] = message
    elseif type(result) == 'table' then
      missing[#missing + 1] = result
    end
  end

  for _, message in ipairs(failures) do
    notify(message, vim.log.levels.ERROR)
  end

  if #missing == 0 then
    notify(('Mason restore found %d package(s) already installed'):format(#entries),
      #failures == 0 and vim.log.levels.INFO or vim.log.levels.ERROR)
    return #failures == 0
  end

  if is_headless() then
    local ok, install_error = pcall(install_missing_blocking, missing)
    if not ok then
      notify(('Mason restore failed: %s'):format(install_error),
        vim.log.levels.ERROR)
      return false
    end

    local check_ok = M.check { lock_path = path }
    return #failures == 0 and check_ok
  end

  notify(('Mason restore installing %d missing package(s)'):format(#missing),
    vim.log.levels.INFO)
  install_missing_interactive(missing, function(install_failures)
    for _, message in ipairs(install_failures) do
      notify(('Mason restore failed: %s'):format(message),
        vim.log.levels.ERROR)
    end
    if #install_failures == 0 then
      notify('Mason restore finished', vim.log.levels.INFO)
    end
  end)

  return #failures == 0
end

function M.setup()
  vim.api.nvim_create_user_command('MasonLock', function()
    M.refresh_lock()
  end, { desc = 'Write mason.lock from installed packages' })

  vim.api.nvim_create_user_command('MasonRestore', function()
    local ok = M.restore()
    if is_headless() then
      vim.cmd('cquit ' .. (ok and '0' or '1'))
    end
  end, { desc = 'Install missing packages from mason.lock' })
end

return M
